# alternatives
# Autogenerated from man page /usr/share/man/man8/alternatives.8.gz
complete -c alternatives -l verbose -d 'Generate more comments about what  alternatives is doing'
complete -c alternatives -l quiet -d 'Don\'t generate any comments unless errors occur'
complete -c alternatives -l test -d 'Don\'t actually do anything, just say what would be done'
complete -c alternatives -l help -d 'Give some usage information (and say which version of  alternatives this is)'
complete -c alternatives -l version -d 'Tell which version of  alternatives this is (and give some usage information)'
complete -c alternatives -l altdir -d 'Specifies the alternatives directory, when this is to be different from the d…'
complete -c alternatives -l admindir -d 'Specifies the administrative directory, when this is to be different from the…'
complete -c alternatives -l install -l slave -l initscript -d 'Add a group of alternatives to the system'
complete -c alternatives -l remove -d 'Remove an alternative and all of its associated slave links'
complete -c alternatives -l set -d 'The symbolic link and slaves for link group name set to those configured for …'
complete -c alternatives -l config -d 'Present the user with a configuration menu for choosing the master link and s…'
complete -c alternatives -l auto -d 'Switch the master symlink  name to automatic mode'
complete -c alternatives -l display -d 'Display information about the link group of which name is the master link'

