# ascii
# Autogenerated from man page /usr/share/man/man1/ascii.1.gz
complete -c ascii -s t -d 'Script-friendly mode, emits only ISO/decimal/hex/octal/binary encodings of th…'
complete -c ascii -s s -d 'Parse multiple characters.  Convenient way of parsing strings'
complete -c ascii -s a -d 'Print in vertical aspect (4 columns by 16 rows) rather than 16x4'
complete -c ascii -s d -d 'Ascii table in decimal'
complete -c ascii -s x -d 'Ascii table in hex'
complete -c ascii -s o -d 'Ascii table in octal'
complete -c ascii -s b -d 'Ascii table in binary'
complete -c ascii -s h -s '?' -d 'Show summary of options and a simple ASCII table'
complete -c ascii -s v -d 'Show version of program'

