# autoupdate-2.71
# Autogenerated from man page /usr/share/man/man1/autoupdate-2.71.1.gz
complete -c 'autoupdate-2.71' -s h -l help -d 'print this help, then exit'
complete -c 'autoupdate-2.71' -s V -l version -d 'print version number, then exit'
complete -c 'autoupdate-2.71' -s v -l verbose -d 'verbosely report processing'
complete -c 'autoupdate-2.71' -s d -l debug -d 'don\'t remove temporary files'
complete -c 'autoupdate-2.71' -s f -l force -d 'consider all files obsolete . SS "Library directories:"'
complete -c 'autoupdate-2.71' -s B -l prepend-include -d 'prepend directory DIR to search path'
complete -c 'autoupdate-2.71' -s I -l include -d 'append directory DIR to search path AUTHOR Written by David J'

