# autoscan-2.71
# Autogenerated from man page /usr/share/man/man1/autoscan-2.71.1.gz
complete -c 'autoscan-2.71' -s h -l help -d 'print this help, then exit'
complete -c 'autoscan-2.71' -s V -l version -d 'print version number, then exit'
complete -c 'autoscan-2.71' -s v -l verbose -d 'verbosely report processing'
complete -c 'autoscan-2.71' -s d -l debug -d 'don\'t remove temporary files . SS "Library directories:"'
complete -c 'autoscan-2.71' -s B -l prepend-include -d 'prepend directory DIR to search path'
complete -c 'autoscan-2.71' -s I -l include -d 'append directory DIR to search path AUTHOR Written by David J'

