# autoconf-2.69
# Autogenerated from man page /usr/share/man/man1/autoconf-2.69.1.gz
complete -c 'autoconf-2.69' -s h -l help -d 'print this help, then exit'
complete -c 'autoconf-2.69' -s V -l version -d 'print version number, then exit'
complete -c 'autoconf-2.69' -s v -l verbose -d 'verbosely report processing'
complete -c 'autoconf-2.69' -s d -l debug -d 'don\'t remove temporary files'
complete -c 'autoconf-2.69' -s f -l force -d 'consider all files obsolete'
complete -c 'autoconf-2.69' -s o -l output -d 'save output in FILE (stdout is the default)'
complete -c 'autoconf-2.69' -s W -l warnings -d 'report the warnings falling in CATEGORY [syntax] '
complete -c 'autoconf-2.69' -s B -l prepend-include -d 'prepend directory DIR to search path'
complete -c 'autoconf-2.69' -s I -l include -d 'append directory DIR to search path . SS "Tracing:"'
complete -c 'autoconf-2.69' -s t -l trace -d 'report the list of calls to MACRO'
complete -c 'autoconf-2.69' -s i -l initialization -d 'also trace Autoconf\'s initialization process'

