# autoreconf-2.71
# Autogenerated from man page /usr/share/man/man1/autoreconf-2.71.1.gz
complete -c 'autoreconf-2.71' -s h -l help -d 'print this help, then exit'
complete -c 'autoreconf-2.71' -s V -l version -d 'print version number, then exit'
complete -c 'autoreconf-2.71' -s v -l verbose -d 'verbosely report processing'
complete -c 'autoreconf-2.71' -s d -l debug -d 'don\'t remove temporary files'
complete -c 'autoreconf-2.71' -s f -l force -d 'consider all generated and standard files obsolete'
complete -c 'autoreconf-2.71' -s i -l install -d 'copy missing standard auxiliary files'
complete -c 'autoreconf-2.71' -l no-recursive -d 'don\'t rebuild sub-packages'
complete -c 'autoreconf-2.71' -s s -l symlink -d 'with -i, install symbolic links instead of copies'
complete -c 'autoreconf-2.71' -s m -l make -d 'when applicable, re-run . /configure && make'
complete -c 'autoreconf-2.71' -s W -l warnings -d 'report the warnings falling in CATEGORY [syntax] '
complete -c 'autoreconf-2.71' -s B -l prepend-include -d 'prepend directory DIR to search path'
complete -c 'autoreconf-2.71' -s I -l include -d 'append directory DIR to search path'

