# cdargs
# Autogenerated from man page /usr/share/man/man1/cdargs.1.gz
complete -c cdargs -s h -l help -d 'display usage information and exit'
complete -c cdargs -s v -l version -d 'output version information and exit'
complete -c cdargs -s a -l add -d 'add path to the bookmarks list using the optional desc as description string'
complete -c cdargs -s f -l file -d 'uses the given FILE as bookmarks file'
complete -c cdargs -s u -l user -d 'read the default bookmarks file of USER.  Won\'t modify that file'
complete -c cdargs -s o -l output -d 'use FILE as the result-file (who knows what The World might make of this feat…'
complete -c cdargs -s b -l browse -d 'start  cdargs in BROWSE mode in the current directory'
complete -c cdargs -s r -l noresolve -d 'Don\'t exit with a result when the Needle matches a description exactly (which…'
complete -c cdargs -s c -l cwd -d 'Make the current working directory the current entry on startup if it appears…'
complete -c cdargs -l nowrap -d 'Don\'t wrap the cursor around when hitting the end of the list'

