# checkX
# Autogenerated from man page /usr/share/man/man1/checkX.1.gz
complete -c checkX -s h -l help -d 'print this help message and exit'
complete -c checkX -s v -l version -d 'print version information and exit'
complete -c checkX -s d -l display -d 'use STRING instead of $DISPLAY'
complete -c checkX -s l -l location -d 'print location of Xlib DLL on stdout'
complete -c checkX -s a -l appendpath -d 'append STRING to value of $PATH (cumulative)'
complete -c checkX -s p -l prependpath -d 'prepend STRING to value of $PATH (cumulative)'
complete -c checkX -s r -l replacepath -d 'use STRING instead of $PATH when searching'
complete -c checkX -s x -l xlibname -d 'use exactly STRING instead of fuzzy cygX11-n. dll search'
complete -c checkX -s t -l timeout -d 'allow FLOAT seconds to connect with Xserver defaults to 0. 5, use 0'
complete -c checkX -l nogui -d 'disable informational popups'
complete -c checkX -l notty -d 'disable stderr messages'
complete -c checkX -l debug -d 'turn on debugging messages'
complete -c checkX -l no-silent -d 'allow error, warning, and info messages'

