# chere
# Autogenerated from man page /usr/share/man/man1/chere.1.gz
complete -c chere -s i -d Install
complete -c chere -s u -d Uninstall
complete -c chere -s x -d 'Refresh eXisting context menu items'
complete -c chere -s l -d 'List currently installed Shell Here'
complete -c chere -s r -d 'Read all  chere registry entries to stdout'
complete -c chere -s a -d 'Operation affects all users'
complete -c chere -s c -d 'Operation affects current user only'
complete -c chere -s n -d 'Be Nice and provide Control Panel uninstall option (Default)'
complete -c chere -s m -d 'Minimal, no Control Panel uninstall'
complete -c chere -s p -d 'Print  regtool commands to stdout rather than running them'
complete -c chere -s f -d 'Force write (overwrite existing, ignore missing files)'
complete -c chere -s 1 -d 'Start shell using registry one-liners'
complete -c chere -s 2 -d 'Start via  bash script'
complete -c chere -s d -d 'Specifies the display to use if xterm or urxvt is specified as the shell'
complete -c chere -s o -d 'Add R options to the terminal startup command'
complete -c chere -s e -d 'Use R menutext as the context menu text'
complete -c chere -s h -d Help
complete -c chere -s v -d Version
complete -c chere -o iuxlrhv -d ') must be specified before chere does anything'

