# clisp
# Autogenerated from man page /usr/share/man/man1/clisp.1.gz
complete -c clisp -o 'h
.br
--help' -d 'Displays a help message on how to invoke \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2'
complete -c clisp -l version -d 'Displays the \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2 version number, as given by the…'
complete -c clisp -l license -d 'Displays a summary of the licensing information, the \\m[blue]GNU\\m[]\\s-2\\u[8]…'
complete -c clisp -o help-image -d 'Displays information about the memory image being invoked: whether is it suit…'
complete -c clisp -s B -d 'Specifies the installation directory'
complete -c clisp -s b -d 'Print the installation directory and exit immediately'
complete -c clisp -s M -d 'Specifies the initial memory image'
complete -c clisp -s L -d 'Specifies the language \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2 uses to communicate w…'
complete -c clisp -s N -d 'Specifies the base directory of locale files'
complete -c clisp -o 'q
.br
--quiet
.br
--silent
.br
-v
.br
--verbose' -d 'Change verbosity level: by default, \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2 displays…'
complete -c clisp -o repl -d 'Start an interactive \\m[blue]read-eval-print loop\\m[]\\s-2\\u[2]\\d\\s+2 after pr…'
complete -c clisp -s w -d 'Wait for a keypress after program termination'
complete -c clisp -s I -d 'Interact better with \\m[blue]Emacs\\m[]\\s-2\\u[23]\\d\\s+2 (useful when running \\…'
complete -c clisp -o disable-readline -d 'Do not use \\m[blue]GNU\\m[]\\s-2\\u[8]\\d\\s+2 \\m[blue]readline\\m[]\\s-2\\u[26]\\d\\s+…'
complete -c clisp -o ansi -d 'Comply with the [ANSI CL standard] specification even where \\m[blue]CLISP\\m[]…'
complete -c clisp -o traditional -d 'Traditional: reverses the residual effects of -ansi in the saved memory image'
complete -c clisp -o modern -d 'Provides a modern view of symbols: at startup the \\m[blue]*PACKAGE*\\m[]\\s-2\\u…'
complete -c clisp -s p -d 'At startup the value of the variable \\m[blue]*PACKAGE*\\m[]\\s-2\\u[28]\\d\\s+2 wi…'
complete -c clisp -s C -d 'Compile when loading: at startup the value of the variable CUSTOM:*LOAD-COMPI…'
complete -c clisp -o norc -d 'Normally \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2 loads the user \\m[blue]\\(lqrun cont…'
complete -c clisp -o lp -d 'Specifies directories to be added to CUSTOM:*LOAD-PATHS* at startup'
complete -c clisp -s i -d 'Specifies initialization files to be \\m[blue]LOAD\\m[]\\s-2\\u[31]\\d\\s+2ed at st…'
complete -c clisp -s c -d 'Compiles the specified lisp-files to bytecode (*. fas)'
complete -c clisp -s o -d 'Specifies the output file or directory for the compilation of the last specif…'
complete -c clisp -s l -d 'Produce a bytecode \\m[blue]DISASSEMBLE\\m[]\\s-2\\u[35]\\d\\s+2 listing (*'
complete -c clisp -s x -d 'Executes a series of arbitrary expressions instead of a \\m[blue]read-eval-pri…'
complete -c clisp -s h
complete -c clisp -l help
complete -c clisp -s K
complete -c clisp -s m
complete -c clisp -o Edomain
complete -c clisp -s q
complete -c clisp -l quiet
complete -c clisp -l silent
complete -c clisp -s v
complete -c clisp -l verbose
complete -c clisp -o on-error
complete -c clisp -l mJohn -d 'When m[blue]CLISPm[]\\u[6]\\d is invoked, the runtime loads the initial memory …'

