# cvsbug
# Autogenerated from man page /usr/share/man/man8/cvsbug.8.gz
complete -c cvsbug -s f -d 'specify a file (problem-report) which already contains a complete problem rep…'
complete -c cvsbug -s t -d 'Change mail address at the support site for problem reports'
complete -c cvsbug -s P -d 'print the form specified by the environment variable   PR_FORM  on standard o…'
complete -c cvsbug -s L -d 'print the list of available categories.   No mail is sent'
complete -c cvsbug -l request-id -d 'sends mail to the default support site, or  site if specified, with a request…'
complete -c cvsbug -s v -d 'Display the  cvsbug version number'

