# cygextreg
# Autogenerated from man page /usr/share/man/man1/cygextreg.1.gz
complete -c cygextreg -s r -l register -d 'Add a file type to the Windows registry'
complete -c cygextreg -s u -l unregister -d 'Remove a file type from the Windows registry'
complete -c cygextreg -l ext -d 'Register or unregister files of the given extension.  Default to . sh'
complete -c cygextreg -l icon -d 'Path and optional index of the icon to register for an extension'
complete -c cygextreg -s a -l all -d 'Register or unregister extension for all users'
complete -c cygextreg -s f -l force -d 'Overwrite if already registered for another application'
complete -c cygextreg -s l -l list -d 'List extensions registered for Cygwin'
complete -c cygextreg -s h -l help -d 'Display help and exit'
complete -c cygextreg -s V -l version -d 'Print version and exit'

