# cygport
# Autogenerated from man page /usr/share/man/man1/cygport.1.gz
complete -c cygport -l 32 -s 4 -d 'build package for i686 Cygwin'
complete -c cygport -l 64 -s 8 -d 'build package for x86_64 Cygwin'
complete -c cygport -l debug -d 'enable debugging messages '

