# dateseq
# Autogenerated from man page /usr/share/man/man1/dateseq.1.gz
complete -c dateseq -s h -l help -d 'Print help and exit'
complete -c dateseq -s V -l version -d 'Print version and exit'
complete -c dateseq -s q -l quiet -d 'Suppress message about date/time and duration parser errors and fix-ups'
complete -c dateseq -s f -l format -d 'Output format'
complete -c dateseq -s i -l input-format -d 'Input format, can be used multiple times'
complete -c dateseq -s b -l base -d 'For underspecified input use DT as a fallback to fill in missing fields'
complete -c dateseq -s e -l backslash-escapes -d 'Enable interpretation of backslash escapes in the output and input format spe…'
complete -c dateseq -l locale -d 'Format results according to LOCALE, this would only affect month and weekday …'
complete -c dateseq -l from-locale -d 'Interpret dates on stdin or the command line as coming from the locale LOCALE…'
complete -c dateseq -s s -l skip -d 'Skip weekdays specified by STRING'
complete -c dateseq -l alt-inc -d 'Alternative increment to use when a date is hit that is skipped as per --skip'
complete -c dateseq -l compute-from-last -d 'Compute a start value from LAST using INCREMENT'

