# datesort
# Autogenerated from man page /usr/share/man/man1/datesort.1.gz
complete -c datesort -s h -l help -d 'Print help and exit'
complete -c datesort -s V -l version -d 'Print version and exit'
complete -c datesort -s i -l input-format -d 'Input format, can be used multiple times'
complete -c datesort -s b -l base -d 'For underspecified input use DT as a fallback to fill in missing fields'
complete -c datesort -s e -l backslash-escapes -d 'Enable interpretation of backslash escapes in the input format specifier stri…'
complete -c datesort -l from-locale -d 'Interpret dates on stdin or the command line as coming from the locale LOCALE…'
complete -c datesort -l from-zone -d 'Interpret dates on stdin or the command line as coming from the time zone ZONE'
complete -c datesort -s r -l reverse -d 'Reverse the sort order'
complete -c datesort -s u -l unique -d 'Print at most one line per date/time value.  FORMAT SPECS'

