# dconv
# Autogenerated from man page /usr/share/man/man1/dconv.1.gz
complete -c dconv -s h -l help -d 'Print help and exit'
complete -c dconv -s V -l version -d 'Print version and exit'
complete -c dconv -s q -l quiet -d 'Suppress message about date/time and duration parser errors and fix-ups'
complete -c dconv -s f -l format -d 'Output format'
complete -c dconv -s i -l input-format -d 'Input format, can be used multiple times'
complete -c dconv -s b -l base -d 'For underspecified input use DT as a fallback to fill in missing fields'
complete -c dconv -s e -l backslash-escapes -d 'Enable interpretation of backslash escapes in the output and input format spe…'
complete -c dconv -s S -l sed-mode -d 'Copy parts from the input before and after a matching date/time'
complete -c dconv -l locale -d 'Format results according to LOCALE, this would only affect month and weekday …'
complete -c dconv -l from-locale -d 'Interpret dates on stdin or the command line as coming from the locale LOCALE…'
complete -c dconv -l from-zone -d 'Interpret dates on stdin or the command line as coming from the time zone ZONE'
complete -c dconv -s z -l zone -d 'Convert dates printed on stdout to time zone ZONE, default: UTC'

