# ddiff
# Autogenerated from man page /usr/share/man/man1/ddiff.1.gz
complete -c ddiff -s h -l help -d 'Print help and exit'
complete -c ddiff -s V -l version -d 'Print version and exit'
complete -c ddiff -s q -l quiet -d 'Suppress message about date/time and duration parser errors and fix-ups'
complete -c ddiff -s S -l skip-illegal -d 'Output empty lines as placeholder for illegal input, i. e'
complete -c ddiff -s f -l format -d 'Output format'
complete -c ddiff -s i -l input-format -d 'Input format, can be used multiple times'
complete -c ddiff -s b -l base -d 'For underspecified input use DT as a fallback to fill in missing fields'
complete -c ddiff -s e -l backslash-escapes -d 'Enable interpretation of backslash escapes in the output and input format spe…'
complete -c ddiff -l from-locale -d 'Interpret dates on stdin or the command line as coming from the locale LOCALE…'
complete -c ddiff -l from-zone -d 'Interpret dates on stdin or the command line as coming from the time zone ZONE'

