# deurlname
# Autogenerated from man page /usr/share/man/man1/deurlname.1.gz
complete -c deurlname -s v -l verbose -d 'Display every rename done'
complete -c deurlname -l help -d 'Show summary of options'
complete -c deurlname -l version -d 'Output version information and exit'

