# dhttpd
# Autogenerated from man page /usr/share/man/man1/dhttpd.1.gz
complete -c dhttpd -s h -d 'Show summary of options'
complete -c dhttpd -s p -d 'Set the port the web server runs on http://servername/ The default location t…'

