# duff
# Autogenerated from man page /usr/share/man/man1/duff.1.gz
complete -c duff -s 0 -d 'If reading file names from stdin, assume they are null-terminated, instead of…'
complete -c duff -s H -d 'Follow symbolic links listed on the command line'
complete -c duff -s L -d 'Follow all symbolic links.  This overrides any previous H or P option'
complete -c duff -s P -d 'Don\'t follow any symbolic links.  This overrides any previous H or L option'
complete -c duff -s a -d 'Include hidden files and directories when searching recursively'
complete -c duff -s d -d 'The message digest function to use'
complete -c duff -s e -d 'Excess mode.  List all but one file from each cluster of duplicates'
complete -c duff -s f -d 'Set the format of the cluster header'
complete -c duff -s h -d 'Display help information and exit'
complete -c duff -s l -d 'The minimum size of files to be sampled'
complete -c duff -s q -d 'Quiet mode.  Suppress warnings and error messages'
complete -c duff -s p -d 'Physical mode.  Make duff consider physical files instead of hard links'
complete -c duff -s r -d 'Recursively search into all specified directories'
complete -c duff -s t -d 'Thorough mode.  Distrust digests as a guarantee for equality'
complete -c duff -s v -d 'Display version information and exit'
complete -c duff -s z -d 'Do not consider empty files to be equal'

