# dzone
# Autogenerated from man page /usr/share/man/man1/dzone.1.gz
complete -c dzone -s h -l help -d 'display this help and exit'
complete -c dzone -s V -l version -d 'output version information and exit'
complete -c dzone -s q -l quiet -d 'Suppress message about date/time or zonename parser errors and fix-ups'
complete -c dzone -s b -l base -d 'For underspecified input use DT as a fallback to fill in missing fields'
complete -c dzone -s i -l input-format -d 'Input format, can be used multiple times'
complete -c dzone -l from-locale -d 'Interpret dates on stdin or the command line as coming from the locale LOCALE…'
complete -c dzone -l from-zone -d 'Interpret dates on stdin or the command line as coming from the time zone ZONE'
complete -c dzone -l next -d 'Show next transition from/to DST'
complete -c dzone -l prev -d 'Show previous transition from/to DST.  FORMAT SPECS'

