# errno
# Autogenerated from man page /usr/share/man/man1/errno.1.gz
complete -c errno -s l -l list -d 'List all errno values'
complete -c errno -s s -l search -d 'Search for errors whose description contains all the given words (case-insens…'
complete -c errno -s S -l search-all-locales -d 'Like --search, but searches all installed locales'

