# flip
# Autogenerated from man page /usr/share/man/man1/flip.1.gz
complete -c flip -s u -d 'Convert to **IX format (CR LF => LF, lone CR or LF unchanged, trailing contr…'
complete -c flip -s m -d 'Convert to MS-DOS format (lone LF => CR LF, lone CR unchanged)'
complete -c flip -s h -d 'Give a help message'
complete -c flip -s v -d 'Be verbose, print filenames as they are processed'
complete -c flip -s t -d 'Touch files (don\'t preserve timestamps)'
complete -c flip -s s -d 'Strip high bit'
complete -c flip -s b -d 'Convert binary files too (else binary files are left unchanged)'
complete -c flip -s z -d 'Truncate file at first control Z encountered'

