# fsck.minix
# Autogenerated from man page /usr/share/man/man8/fsck.minix.8.gz
complete -c 'fsck.minix' -s l -l list -d 'List all filenames'
complete -c 'fsck.minix' -s r -l repair -d 'Perform interactive repairs'
complete -c 'fsck.minix' -s a -l auto -d 'Perform automatic repairs'
complete -c 'fsck.minix' -s v -l verbose -d 'Be verbose'
complete -c 'fsck.minix' -s s -l super -d 'Output super-block information'
complete -c 'fsck.minix' -s m -l uncleared -d 'Activate MINIX-like "mode not cleared" warnings'
complete -c 'fsck.minix' -s f -l force -d 'Force a filesystem check even if the filesystem was marked as valid'
complete -c 'fsck.minix' -s V -l version -d 'Display version information and exit'
complete -c 'fsck.minix' -s h -l help -d 'Display help text and exit'

