# fsck.cramfs
# Autogenerated from man page /usr/share/man/man8/fsck.cramfs.8.gz
complete -c 'fsck.cramfs' -s v -l verbose -d 'Enable verbose messaging'
complete -c 'fsck.cramfs' -s b -l blocksize -d 'Use this blocksize, defaults to page size'
complete -c 'fsck.cramfs' -l extract -d 'Test to uncompress the whole file system'
complete -c 'fsck.cramfs' -s a -d 'This option is silently ignored'
complete -c 'fsck.cramfs' -s y -d 'This option is silently ignored'
complete -c 'fsck.cramfs' -s V -l version -d 'Display version information and exit'
complete -c 'fsck.cramfs' -s h -l help -d 'Display help text and exit.  EXIT STATUS 0 success'

