# gio
# Autogenerated from man page /usr/share/man/man1/gio.1.gz
complete -c gio -s T -l no-target-directory
complete -c gio -s p -l progress
complete -c gio -s i -l interactive
complete -c gio -l preserve
complete -c gio -s b -l backup
complete -c gio -s P -l no-dereference
complete -c gio -s w -l query-writable
complete -c gio -s f -l filesystem
complete -c gio -s a -l attributes
complete -c gio -s n -l nofollow-symlinks
complete -c gio -s h -l hidden
complete -c gio -s l -l long
complete -c gio -s u -l print-uris
complete -c gio -l parent
complete -c gio -s d -l dir
complete -c gio -l file
complete -c gio -s D -l direct
complete -c gio -s s -l silent
complete -c gio -l no-moves
complete -c gio -s m -l mounts
complete -c gio -l mountable
complete -c gio -l device
complete -c gio -l unmount
complete -c gio -s e -l eject
complete -c gio -l unmount-scheme
complete -c gio -l force
complete -c gio -l anonymous
complete -c gio -l list
complete -c gio -s o -l monitor
complete -c gio -l detail
complete -c gio -s c -l create
complete -c gio -l append
complete -c gio -l private
complete -c gio -l unlink
complete -c gio -s v -l print-etag
complete -c gio -l etag
complete -c gio -s t -l type
complete -c gio -l empty
complete -c gio -l follow-symlinks

