# icmd
# Autogenerated from man page /usr/share/man/man1/icmd.1.gz
complete -c icmd -l command -d 'Specify command to run instead of the default `mv\' or `cp\''
complete -c icmd -l arg-options -d 'Specify what comma-separated options for mv, cp, or the command specified wit…'
complete -c icmd -l pass-through -d 'Run mv/cp (or the command specified with --command) if two or more arguments …'
complete -c icmd -l help -d 'Show summary of options'
complete -c icmd -l version -d 'Output version information and exit'

