# ifnames-2.69
# Autogenerated from man page /usr/share/man/man1/ifnames-2.69.1.gz
complete -c 'ifnames-2.69' -s h -l help -d 'print this help, then exit'
complete -c 'ifnames-2.69' -s V -l version -d 'print version number, then exit AUTHOR Written by David J'

