# ipcrm
# Autogenerated from man page /usr/share/man/man1/ipcrm.1.gz
complete -c ipcrm -s M -d 'Mark the shared memory segment associated with key ipcrm shmkey for removal'
complete -c ipcrm -s m -d 'Mark the shared memory segment associated with ID ipcrm shmid for removal'
complete -c ipcrm -s Q -d 'Remove the message queue associated with key ipcrm msgkey from the system'
complete -c ipcrm -s q -d 'Remove the message queue associated with the ID ipcrm msqid from the system'
complete -c ipcrm -s S -d 'Remove the semaphore set associated with key ipcrm semkey from the system'
complete -c ipcrm -s s -d 'Removes the semaphore set associated with ID ipcrm semid from the system'

