# isutf8
# Autogenerated from man page /usr/share/man/man1/isutf8.1.gz
complete -c isutf8 -s h -l help -d 'Print out a help summary'
complete -c isutf8 -s q -l quiet -d 'Don\\*(Aqt print messages telling which files are invalid UTF-8, merely indica…'
complete -c isutf8 -s l -l list -d 'Print only the names of files containing invalid UTF-8'
complete -c isutf8 -s i -l invert -d 'Invert the selection: list UTF-8 compatible files'
complete -c isutf8 -s v -l verbose -d 'Also print an hexdump-like view of the error and some context'

