# lastlog
# Autogenerated from man page /usr/share/man/man8/lastlog.8.gz
complete -c lastlog -s b -l beforeDAYS -d 'Print only lastlog records older than DAYS'
complete -c lastlog -s h -l help -d 'Display help message and exit'
complete -c lastlog -s t -l timeDAYS -d 'Print the lastlog records more recent than DAYS'
complete -c lastlog -s u -l userLOGIN -d 'Print the lastlog record of the specified user(s)'
complete -c lastlog -l before
complete -c lastlog -l time
complete -c lastlog -l user

