# lckdo
# Autogenerated from man page /usr/share/man/man1/lckdo.1.gz
complete -c lckdo -s w -d 'If the lock is already held by another process, wait for it to complete inste…'
complete -c lckdo -s W -d 'The same as -w but wait not more than sec seconds'
complete -c lckdo -s e -d 'Execute the program directly without forking and waiting (keeps an extra file…'
complete -c lckdo -s E -d 'Set the file descriptor number to keep open when exec()ing (implies -e)'
complete -c lckdo -s n -d 'Do not create the lock file if it does not exist'
complete -c lckdo -s q -d 'Produce no output if lock is already held'
complete -c lckdo -s s -d 'Lock in shared (read) mode'
complete -c lckdo -s x -d 'Lock in exclusive (write) mode (default)'
complete -c lckdo -s t -d 'Test for lock existence'

