# lockfile
# Autogenerated from man page /usr/share/man/man1/lockfile.1.gz
complete -c lockfile -o r-1 -d 'lockfile will retry forever'
complete -c lockfile -s f
complete -c lockfile -o ml -d and
complete -c lockfile -o mu -d respectively

