# login
# Autogenerated from man page /usr/share/man/man1/login.1.gz
complete -c login -s p -d 'Used by  getty (8) to tell  login not to destroy the environment'
complete -c login -s f -d 'Used to skip a second login authentication'
complete -c login -s h -d 'Used by other servers (i. e'

