# lpr
# Autogenerated from man page /usr/share/man/man1/lpr.1.gz
complete -c lpr -s D -d 'enables some debugging output'
complete -c lpr -s d -d 'specifies the device to which to send the output'
complete -c lpr -s h -d 'does nothing and is accepted for compatibility only'
complete -c lpr -s l -d 'disables CR/LF translation'
complete -c lpr -s P -d 'an alias for -d'

