# makepasswd
# Autogenerated from man page /usr/share/man/man1/makepasswd.1.gz
complete -c makepasswd -l chars -d 'Generate passwords with exactly N characters (do not use with options --minch…'
complete -c makepasswd -l clearfrom -d 'Use password from FILE instead of generating passwords'
complete -c makepasswd -l count -d 'Produce a total of N passwords (the default is one)'
complete -c makepasswd -l crypt -d 'Produce encrypted passwords'
complete -c makepasswd -l cryptsalt -d 'Use crypt() salt N, a positive number <= 4096'
complete -c makepasswd -l help -d 'Ignore other operands and produce only a help display'
complete -c makepasswd -l maxchars -d 'Generate passwords with at most N characters (default = 8)'
complete -c makepasswd -l minchars -d 'Generate passwords with at least N characters (default = 6)'
complete -c makepasswd -l nocrypt -d 'Do not encrypt the generated password(s) (the default)'
complete -c makepasswd -l noverbose -d 'Display no labels on output (the default)'
complete -c makepasswd -l randomseed -d 'Use random number seed N, between 0 and 2^32 inclusive'
complete -c makepasswd -l rerandom -d 'Set the random seed value every N values used'
complete -c makepasswd -l repeatpass -d 'Use each password N times (4096 maximum, --crypt must be set and --cryptsalt …'
complete -c makepasswd -l string -d 'Use the characters in STRING to generate random passwords'
complete -c makepasswd -l verbose -d 'Display labelling information on output.  HISTORY'

