# mkfs.bfs
# Autogenerated from man page /usr/share/man/man8/mkfs.bfs.8.gz
complete -c 'mkfs.bfs' -s N -l inodes -d 'Specify the desired number of inodes (at most 512)'
complete -c 'mkfs.bfs' -s V -l vname -d 'Specify the volume label.   I have no idea if/where this is used'
complete -c 'mkfs.bfs' -s F -l fname -d 'Specify the filesystem name.   I have no idea if/where this is used'
complete -c 'mkfs.bfs' -s v -l verbose -d 'Explain what is being done'
complete -c 'mkfs.bfs' -s c -d 'This option is silently ignored'
complete -c 'mkfs.bfs' -s l -d 'This option is silently ignored'
complete -c 'mkfs.bfs' -s h -l help -d 'Display help text and exit'
complete -c 'mkfs.bfs' -l version -d 'Display version information and exit.  Option'

