# mkfs
# Autogenerated from man page /usr/share/man/man8/mkfs.8.gz
complete -c mkfs -s t -l type -d 'Specify the type of filesystem to be built'
complete -c mkfs -s V -l verbose -d 'Produce verbose output, including all filesystem-specific commands that are e…'
complete -c mkfs -l version -d 'Display version information and exit'
complete -c mkfs -s h -l help -d 'Display help text and exit'

