# mkfs.minix
# Autogenerated from man page /usr/share/man/man8/mkfs.minix.8.gz
complete -c 'mkfs.minix' -s c -l check -d 'Check the device for bad blocks before creating the filesystem'
complete -c 'mkfs.minix' -s n -l namelength -d 'Specify the maximum length of filenames'
complete -c 'mkfs.minix' -s i -l inodes -d 'Specify the number of inodes for the filesystem'
complete -c 'mkfs.minix' -s l -l badblocks -d 'Read the list of bad blocks from R filename '
complete -c 'mkfs.minix' -s 1 -d 'Make a Minix version 1 filesystem.   This is the default'
complete -c 'mkfs.minix' -s 2 -s v -d 'Make a Minix version 2 filesystem'
complete -c 'mkfs.minix' -s 3 -d 'Make a Minix version 3 filesystem'
complete -c 'mkfs.minix' -s V -l version -d 'Display version information and exit'
complete -c 'mkfs.minix' -s h -l help -d 'Display help text and exit.  EXIT CODES The exit code returned by mkfs'

