# mkfs.cramfs
# Autogenerated from man page /usr/share/man/man8/mkfs.cramfs.8.gz
complete -c 'mkfs.cramfs' -s v -d 'Enable verbose messaging'
complete -c 'mkfs.cramfs' -s E -d 'Treat all warnings as errors, which are reflected as command return value'
complete -c 'mkfs.cramfs' -s b -d 'Use defined block size, which has to be divisible by page size'
complete -c 'mkfs.cramfs' -s e -d 'Use defined file system edition number in superblock'
complete -c 'mkfs.cramfs' -s N -d 'Use defined endianness.   Value defaults to R host '
complete -c 'mkfs.cramfs' -s i -d 'Insert a  file to cramfs file system'
complete -c 'mkfs.cramfs' -s n -d 'Set name of the cramfs file system'
complete -c 'mkfs.cramfs' -s p -d 'Pad by 512 bytes for boot code'
complete -c 'mkfs.cramfs' -s s -d 'This option is ignored.   Originally the -s turned on directory entry sorting'
complete -c 'mkfs.cramfs' -s z -d 'Make explicit holes'
complete -c 'mkfs.cramfs' -s h -l help -d 'Display help text and exit'
complete -c 'mkfs.cramfs' -s V -l version -d 'Display version information and exit.  EXIT STATUS 0 success'

