# mkshortcut
# Autogenerated from man page /usr/share/man/man1/mkshortcut.1.gz
complete -c mkshortcut -s a -l arguments -d 'Arguments to use (see example below)'
complete -c mkshortcut -s d -l desc -d 'Text for description/tooltip (defaults to POSIX path of TARGET)'
complete -c mkshortcut -s h -l help -d 'Output usage information (to stdout) and exit'
complete -c mkshortcut -s i -l icon -d 'Specify ICONFILE containing the icon to use for the shortcut; defaults to TAR…'
complete -c mkshortcut -s j -l iconoffset -d 'Requires -i.  Use NUM icon in ICONFILE, offset from 0.  Defaults to 0'
complete -c mkshortcut -s n -l name -d 'Name to use for the shortcut file'
complete -c mkshortcut -s s -l show -d 'For norm, min, and max the new window will be normal, minimized, and  maximiz…'
complete -c mkshortcut -s w -l workingdir -d 'PATH to use for the working directory (defaults to directory path of TARGET)'
complete -c mkshortcut -s v -l version -d 'Output version information (to stdout) and exit'
complete -c mkshortcut -s A -l allusers -d 'Requires either -D or -P'
complete -c mkshortcut -s D -l desktop -d 'Instead of creating the shortcut relative to the current directory, create it…'
complete -c mkshortcut -s P -l smprograms -d 'Instead of creating the shortcut relative to the current directory, create it…'

