# mkvmerge
# Autogenerated from man page /usr/share/man/man1/mkvmerge.1.gz
complete -c mkvmerge -s v -l verbose
complete -c mkvmerge -s q -l quiet
complete -c mkvmerge -s o -l output
complete -c mkvmerge -l split -d 'option for details'
complete -c mkvmerge -s w -l webm
complete -c mkvmerge -l title
complete -c mkvmerge -l default-language
complete -c mkvmerge -l language -d 'option and for which the source container doesnt provide a language'
complete -c mkvmerge -l segmentinfo
complete -c mkvmerge -l segment-uid
complete -c mkvmerge -l chapter-language
complete -c mkvmerge -l generate-chapters
complete -c mkvmerge -l chapter-charset
complete -c mkvmerge -l generate-chapters-name-template
complete -c mkvmerge -l cue-chapter-name-format -d 'mkvmerge(1) supports reading CUE sheets for audio files as the input for chap…'
complete -c mkvmerge -l chapters
complete -c mkvmerge -l global-tags
complete -c mkvmerge -l track-order
complete -c mkvmerge -l cluster-length
complete -c mkvmerge -l no-cues
complete -c mkvmerge -l cues -d 'which can be specified for each input file'
complete -c mkvmerge -l clusters-in-meta-seek
complete -c mkvmerge -l disable-lacing
complete -c mkvmerge -l enable-durations
complete -c mkvmerge -l disable-track-statistics-tags
complete -c mkvmerge -l timestamp-scale
complete -c mkvmerge -s 1
complete -c mkvmerge -l link
complete -c mkvmerge -l link-to-previous
complete -c mkvmerge -l link-to-next
complete -c mkvmerge -l append-mode
complete -c mkvmerge -l append-to
complete -c mkvmerge -l attachment-description
complete -c mkvmerge -l attach-file -d or
complete -c mkvmerge -l attach-file-once -d option
complete -c mkvmerge -l attachment-mime-type -d 'MIME type of the following attachment.  Applies to the next'
complete -c mkvmerge -l attachment-name
complete -c mkvmerge -s a -l audio-tracks
complete -c mkvmerge -l identify -d 'switch.  Theyre not simply the track numbers (see section track IDs)'
complete -c mkvmerge -s d -l video-tracks
complete -c mkvmerge -s s -l subtitle-tracks
complete -c mkvmerge -s b -l button-tracks
complete -c mkvmerge -l track-tags
complete -c mkvmerge -s m -l attachments
complete -c mkvmerge -s A -l no-audio
complete -c mkvmerge -s D -l no-video
complete -c mkvmerge -s S -l no-subtitles
complete -c mkvmerge -s B -l no-buttons
complete -c mkvmerge -s T -l no-track-tags
complete -c mkvmerge -l no-chapters
complete -c mkvmerge -s M -l no-attachments
complete -c mkvmerge -l no-global-tags
complete -c mkvmerge -s y -l sync
complete -c mkvmerge -l default-track
complete -c mkvmerge -l forced-track
complete -c mkvmerge -l blockadd
complete -c mkvmerge -l track-name
complete -c mkvmerge -l list-languages -d option
complete -c mkvmerge -s t -l tags
complete -c mkvmerge -l aac-is-sbr
complete -c mkvmerge -l reduce-to-core
complete -c mkvmerge -l remove-dialog-normalization-gain
complete -c mkvmerge -l timestamps
complete -c mkvmerge -l default-duration
complete -c mkvmerge -l fix-bitstream-timing-information
complete -c mkvmerge -l nalu-size-length
complete -c mkvmerge -l compression
complete -c mkvmerge -s f -l fourcc
complete -c mkvmerge -l display-dimensions -d 'Matroska files contain two values that set the display properties that a play…'
complete -c mkvmerge -l aspect-ratio -d 'or the'
complete -c mkvmerge -l aspect-ratio-factor -d 'option (see below).  These options are mutually exclusive'
complete -c mkvmerge -l cropping
complete -c mkvmerge -l colour-matrix
complete -c mkvmerge -l colour-bits-per-channel
complete -c mkvmerge -l chroma-subsample
complete -c mkvmerge -l cb-subsample
complete -c mkvmerge -l chroma-siting
complete -c mkvmerge -l colour-range
complete -c mkvmerge -l colour-transfer-characteristics
complete -c mkvmerge -l colour-primaries
complete -c mkvmerge -l max-content-light
complete -c mkvmerge -l max-frame-light
complete -c mkvmerge -l chromaticity-coordinates
complete -c mkvmerge -l white-colour-coordinates
complete -c mkvmerge -l max-luminance
complete -c mkvmerge -l min-luminance
complete -c mkvmerge -l projection-type
complete -c mkvmerge -l projection-private
complete -c mkvmerge -l projection-pose-yaw
complete -c mkvmerge -l projection-pose-pitch
complete -c mkvmerge -l projection-pose-roll
complete -c mkvmerge -l field-order
complete -c mkvmerge -l stereo-mode
complete -c mkvmerge -l sub-charset
complete -c mkvmerge -s i
complete -c mkvmerge -l identification-format
complete -c mkvmerge -s J
complete -c mkvmerge -s F
complete -c mkvmerge -l ui-language -d ' 2. c   2.  4. 2'
complete -c mkvmerge -l probe-range-percentage
complete -c mkvmerge -s l -l list-types
complete -c mkvmerge -l priority
complete -c mkvmerge -l command-line-charset
complete -c mkvmerge -l output-charset
complete -c mkvmerge -s r -l redirect-output
complete -c mkvmerge -l debug
complete -c mkvmerge -l engage
complete -c mkvmerge -l gui-mode
complete -c mkvmerge -l capabilities
complete -c mkvmerge -s h -l help
complete -c mkvmerge -s V -l version

