# mptopdf
# Autogenerated from man page /usr/share/man/man1/mptopdf.1.gz
complete -c mptopdf -l metafun -d 'use the metafun format to process the file (default is mpost)'
complete -c mptopdf -l texexec -d 'use texexec (context) to process text snippets'
complete -c mptopdf -l latex -d 'use latex to process text snippets AUTHOR More information about ConTeXt and …'

