# ncdu
# Autogenerated from man page /usr/share/man/man1/ncdu.1.gz
complete -c ncdu -s h -d 'Print a short help message and quit'
complete -c ncdu -s v -d 'Print ncdu version and quit'
complete -c ncdu -s f -d 'Load the given file, which has earlier been created with the \\f(CW\\*(C`-o\\*(C…'
complete -c ncdu -s o -d 'Export all necessary information to \\s-1FILE\\s0 instead of opening the browse…'
complete -c ncdu -s 0 -d 'Don\'t give any feedback while scanning a directory or importing a file, other…'
complete -c ncdu -s 1 -d 'Similar to \\f(CW\\*(C`-0\\*(C\', but does give feedback on the scanning progress…'
complete -c ncdu -s 2 -d 'Provide a full-screen ncurses interface while scanning a directory or importi…'
complete -c ncdu -s q -d 'Quiet mode'
complete -c ncdu -s r -d 'Read-only mode.  This will disable the built-in file deletion feature'
complete -c ncdu -s x -d 'Do not cross filesystem boundaries, i. e'
complete -c ncdu -l exclude -d 'Exclude files that match \\s-1PATTERN\\s0'
complete -c ncdu -s X -l exclude-from -d 'Exclude files that match any pattern in \\s-1FILE\\s0'

