# nologin
# Autogenerated from man page /usr/share/man/man8/nologin.8.gz
complete -c nologin -s h -l help -d 'Display help text and exit'
complete -c nologin -s V -l version -d 'Display version information and exit'

