# parallel
# Autogenerated from man page /usr/share/man/man1/parallel.1.gz
complete -c parallel -s j -d 'Use to limit the number of jobs that are run at the same time'
complete -c parallel -s l -d 'Wait as needed to avoid starting new jobs when the system\\*(Aqs load average …'
complete -c parallel -s i -d 'Normally the command is passed the argument at the end of its command line'
complete -c parallel -s n -d 'Number of arguments to pass to a command at a time.  Default is 1'

