# pg_amcheck
# Autogenerated from man page /usr/share/man/man1/pg_amcheck.1.gz
complete -c pg_amcheck -o 'a
.br
--all' -d 'Check all databases, except for any excluded via --exclude-database'
complete -c pg_amcheck -s d -d 'Check databases matching the specified pattern, except for any excluded by --…'
complete -c pg_amcheck -s D -d 'Exclude databases matching the given pattern'
complete -c pg_amcheck -s i -d 'Check indexes matching the specified pattern, unless they are otherwise exclu…'
complete -c pg_amcheck -s I -d 'Exclude indexes matching the specified pattern'
complete -c pg_amcheck -s r -d 'Check relations matching the specified pattern, unless they are otherwise exc…'
complete -c pg_amcheck -s R -d 'Exclude relations matching the specified pattern'
complete -c pg_amcheck -s s -d 'Check tables and indexes in schemas matching the specified pattern, unless th…'
complete -c pg_amcheck -s S -d 'Exclude tables and indexes in schemas matching the specified pattern'
complete -c pg_amcheck -s t -d 'Check tables matching the specified pattern, unless they are otherwise exclud…'
complete -c pg_amcheck -s T -d 'Exclude tables matching the specified pattern'
complete -c pg_amcheck -l no-dependent-indexes -d 'By default, if a table is checked, any btree indexes of that table will also …'
complete -c pg_amcheck -l no-dependent-toast -d 'By default, if a table is checked, its toast table, if any, will also be chec…'
complete -c pg_amcheck -l no-strict-names -d 'By default, if an argument to --database, --table, --index, or --relation mat…'
complete -c pg_amcheck -l exclude-toast-pointers -d 'By default, whenever a toast pointer is encountered in a table, a lookup is p…'
complete -c pg_amcheck -l on-error-stop -d 'After reporting all corruptions on the first page of a table where corruption…'
complete -c pg_amcheck -l skip -d 'If all-frozen is given, table corruption checks will skip over pages in all t…'
complete -c pg_amcheck -l startblock -d 'Start checking at the specified block number'
complete -c pg_amcheck -l endblock -d 'End checking at the specified block number'
complete -c pg_amcheck -l heapallindexed -d 'For each index checked, verify the presence of all heap tuples as index tuple…'
complete -c pg_amcheck -l parent-check -d 'For each btree index checked, use amcheck\\*(Aqs bt_index_parent_check functio…'
complete -c pg_amcheck -l rootdescend -d 'For each index checked, re-find tuples on the leaf level by performing a new …'
complete -c pg_amcheck -l all
complete -c pg_amcheck -l database -d and
complete -c pg_amcheck -l exclude-database
complete -c pg_amcheck -l relation
complete -c pg_amcheck -l exclude-relation
complete -c pg_amcheck -l table
complete -c pg_amcheck -l exclude-table
complete -c pg_amcheck -l index
complete -c pg_amcheck -l exclude-index -d 'mydb*. myschema*. myrel*).  Finally, they include'
complete -c pg_amcheck -l schema -d and
complete -c pg_amcheck -l exclude-schema -d 'when such options are used with a two-part pattern (e. g.  mydb*. myschema*)'
complete -c pg_amcheck -s a
complete -c pg_amcheck -s h
complete -c pg_amcheck -l host
complete -c pg_amcheck -s p
complete -c pg_amcheck -l port
complete -c pg_amcheck -s U
complete -c pg_amcheck -l username
complete -c pg_amcheck -s w
complete -c pg_amcheck -l no-password
complete -c pg_amcheck -s W
complete -c pg_amcheck -l password
complete -c pg_amcheck -l maintenance-db
complete -c pg_amcheck -s e
complete -c pg_amcheck -l echo
complete -c pg_amcheck -s j
complete -c pg_amcheck -l jobs
complete -c pg_amcheck -s P
complete -c pg_amcheck -l progress
complete -c pg_amcheck -s v
complete -c pg_amcheck -l verbose
complete -c pg_amcheck -s V
complete -c pg_amcheck -l version
complete -c pg_amcheck -l install-missing
complete -c pg_amcheck -s '?'
complete -c pg_amcheck -l help

