# procmail
# Autogenerated from man page /usr/share/man/man1/procmail.1.gz
complete -c procmail -s v -d 'Procmail will print its version number, display its compile time configuratio…'
complete -c procmail -s p -d 'Preserve any old environment'
complete -c procmail -s t -d 'Make procmail fail softly, i. e'
complete -c procmail -s f -d 'Causes procmail to regenerate the leading `From \' line with  fromwhom as the …'
complete -c procmail -s o -d 'Instead of allowing anyone to generate `From \' lines, simply override the fak…'
complete -c procmail -s Y -d 'Assume traditional Berkeley mailbox format, ignore any  Content-Length: fields'
complete -c procmail -s a -d 'This will set $1 to be equal to R argument '
complete -c procmail -s d -d 'This turns on explicit delivery mode, delivery will be to the local user R re…'
complete -c procmail -s m -d 'Turns procmail into a general purpose mail filter'

