# pstoedit
# Autogenerated from man page /usr/share/man/man1/pstoedit.1.gz
complete -c pstoedit -o include -d 'This option allows specifying an additional PostScript file that will be exec…'
complete -c pstoedit -o xscale -d PP
complete -c pstoedit -o yscale -d PP
complete -c pstoedit -o xshift -d PP
complete -c pstoedit -o yshift -d PP
complete -c pstoedit -o minlinewidth -d PP
complete -c pstoedit -o pagenumberformat -d PP
complete -c pstoedit -o page -d 'Select a single page from a multi-page PostScript or PDF file. PP'
complete -c pstoedit -o rotate -d 'Rotate image by angle. PP'
complete -c pstoedit -o pagesize -d 'set page size for output medium'
complete -c pstoedit -o gs -d PP
complete -c pstoedit -o psarg -d 'The string given with this option is passed directly to Ghostscript when Ghos…'
complete -c pstoedit -o pslanguagelevel -d PP
complete -c pstoedit -s f -d 'target output format recognized by pstoedit'
complete -c pstoedit -o gsregbase -d 'registry path to use as a base path when searching Ghostscript interpreter'
complete -c pstoedit -o df -d 'Sometimes fonts embedded in a PostScript program do not have a fontname'
complete -c pstoedit -o pngimage -d PP
complete -c pstoedit -o uchar -d 'Sometimes pstoedit cannot map a character from the encoding used by the PostS…'
complete -c pstoedit -o fontmap -d 'The font map is a simple text file containing lines in the following format: '
complete -c pstoedit -o flat -d 'If the output format does not support curves in the way PostScript does or if…'
complete -c pstoedit -o vl -d 'Switch on verbose mode with a given level'
complete -c pstoedit -o bo -d 'dumpfile outfile'
complete -c pstoedit -o help -s v
complete -c pstoedit -o sclip -d 'option to simulate clipping'

