# rclock
# Autogenerated from man page /usr/share/man/man1/rclock.1.gz
complete -c rclock -o display -d 'Attempt to open a window on the named X display'
complete -c rclock -o geometry -d 'Create the window with the specified X window geometry [default 80x80]'
complete -c rclock -o bg -d 'Window background color [default white]'
complete -c rclock -o fg -d 'Window foreground color [default black]'
complete -c rclock -o fn -d 'Select font used for reminders [default 7x14]'
complete -c rclock -o nodate -d 'Do not display today\'s date on the face of the clock'
complete -c rclock -o iconic -d 'Start iconified, if supported by the window manager'
complete -c rclock -o adjust -d 'Adjust the clock by +/-  ddhhmm '
complete -c rclock -o update -d 'Update clock face every  n seconds [default 30]'
complete -c rclock -o mail -d 'Check for new mail every  n seconds [default 60]'
complete -c rclock -o mailfile -d 'Override environmental variable MAIL with  mailfile as location for mail'
complete -c rclock -o mailspawn -d 'Execute  cmd when the face of the clock is clicked by the mouse button'

