# readshortcut
# Autogenerated from man page /usr/share/man/man1/readshortcut.1.gz
complete -c readshortcut -s h -l help -d 'Output detailed usage information and exit'
complete -c readshortcut -l usage -d 'Output basic usage information and exit'
complete -c readshortcut -s v -l version -d 'Display the program version and exit'
complete -c readshortcut -l license -d 'Display the license agreement and exit'
complete -c readshortcut -s f -l fields -d 'Show field names (Target, Working Directory, Arguments, Show Command, Icon Li…'
complete -c readshortcut -s u -l unix -d 'Use Unix path format for display (default)'
complete -c readshortcut -s w -l windows -d 'Use Windows path format for display'
complete -c readshortcut -s t -l target -d 'Display shortcut target (default)'
complete -c readshortcut -s g -l working -d 'Display shortcut working directory'
complete -c readshortcut -s r -l args -d 'Display shortcut arguments'
complete -c readshortcut -s s -l showcmd -d 'Display shortcut "show" command value (Normal, Minimized, or Maximized)'
complete -c readshortcut -s i -l icon -d 'Display icon library location'
complete -c readshortcut -s j -l offset -d 'Display icon library offset'
complete -c readshortcut -s d -l desc -d 'Display shortcut description'
complete -c readshortcut -s a -l all -d 'Display all information'
complete -c readshortcut -s R -l raw -d 'Show paths in raw mode (that is, without expanding embedded environment varia…'

