# reboot
# Autogenerated from man page /usr/share/man/man8/reboot.8.gz
complete -c reboot -s f -l force -d 'Forces the execution.  This can cause applications to lose data'
complete -c reboot -s i -l install -d 'Install Windows Updates during shutdown or reboot'
complete -c reboot -s H -l hybrid -d 'Shutdown in hybrid mode and prepare it for fast startup'
complete -c reboot -s x -l exitex -d 'Use ExitWindowsEx rather than InitiateSystemShutdownEx or InitiateShutdown'
complete -c reboot -l help -d 'Display a help text and exit'
complete -c reboot -l version -d 'Display version information and exit'

