# Rscript
# Autogenerated from man page /usr/share/man/man1/Rscript.1.gz
complete -c Rscript -l help -d 'Print usage and exit'
complete -c Rscript -l version -d 'Print version and exit'
complete -c Rscript -l verbose -d 'Print information on progress'
complete -c Rscript -l default-packages -d 'Attach these packages on startup; a comma-separated LIST of package names, or…'
complete -c Rscript -l save -d 'Do save workspace at the end of the session'
complete -c Rscript -l no-environ -d 'Don\'t read the site and user environment files'
complete -c Rscript -l no-site-file -d 'Don\'t read the site-wide Rprofile'
complete -c Rscript -l no-init-file -d 'Don\'t read the user R profile'
complete -c Rscript -l restore -d 'Do restore previously saved objects at startup'
complete -c Rscript -l vanilla -d 'Combine --no-save, --no-restore, --no-site-file,'

