# run
# Autogenerated from man page /usr/share/man/man1/run.1.gz
complete -c run -s p -d 'you can add  path to the PATH environment variable'
complete -c run -l wait -d 'as first program  argument will make  run  wait for program completition, oth…'
complete -c run -l quote -d 'option enables automatic quoting of arguments with embedded whitespace, doubl…'
complete -c run -o wait -d and
complete -c run -o quote -d 'can be issued with a single leading dash'

