# run2
# Autogenerated from man page /usr/share/man/man1/run2.1.gz
complete -c run2 -s h -l help -d 'print this help message and exit'
complete -c run2 -s v -l version -d 'print version information and exit'
complete -c run2 -s d -l display -d 'use STRING instead of $DISPLAY'
complete -c run2 -s x -l xlibname -d 'use exactly STRING instead of fuzzy cygX11-n. dll search'
complete -c run2 -s t -l timeout -d 'allow FLOAT seconds to connect with Xserver defaults to 0. 5, use 0'
complete -c run2 -l force-gdi -d 'unconditionally launch GDI configuration'
complete -c run2 -l force-x11 -d 'unconditionally launch X11 configuration'
complete -c run2 -s w -l wait -d 'wait for the target app to complete before returning'
complete -c run2 -l nogui -d 'disable informational popups'
complete -c run2 -l notty -d 'disable stderr messages'
complete -c run2 -l silent -d 'suppress all but fatal error messages (default)'
complete -c run2 -l no-silent -d 'allow (fatal and non-fatal) error messages'
complete -c run2 -l no-verbose -d 'same as --no-silent'
complete -c run2 -l verbose -d 'allow error, warning, and info messages'
complete -c run2 -l debug -d 'turn on debugging messages, as well as those enabled by --verbose'

