# shutdown
# Autogenerated from man page /usr/share/man/man8/shutdown.8.gz
complete -c shutdown -s f -l force -d 'Forces the execution.  This can cause applications to lose data'
complete -c shutdown -s h -l halt -d 'The system will shutdown and power off.  This is the default action'
complete -c shutdown -s s -l shutdown -d 'Same as --halt'
complete -c shutdown -s r -l reboot -d 'The system will shutdown and then restart'
complete -c shutdown -s b -l hibernate -d 'The system will suspend to disk'
complete -c shutdown -s p -l suspend -d 'The system will suspend to RAM.  This is also known as sleep or standby'
complete -c shutdown -s i -l install -d 'Install Windows Updates during shutdown or reboot'
complete -c shutdown -s H -l hybrid -d 'Shutdown in hybrid mode and prepare it for fast startup'
complete -c shutdown -s c -l cancel -d 'Aborts the execution of formerly started shutdown or reboot'
complete -c shutdown -s a -l abort -d 'Same as --cancel'
complete -c shutdown -s x -l exitex -d 'Use ExitWindowsEx rather than InitiateSystemShutdownEx or InitiateShutdown'
complete -c shutdown -l help -d 'Display a help text and exit'
complete -c shutdown -l version -d 'Display version information and exit'

