# strptime
# Autogenerated from man page /usr/share/man/man1/strptime.1.gz
complete -c strptime -s h -l help -d 'Print help and exit'
complete -c strptime -s V -l version -d 'Print version and exit'
complete -c strptime -s t -l time -d 'also display time in the output, default is to display the date'
complete -c strptime -s q -l quiet -d 'Suppress message about date/time and duration parser errors'
complete -c strptime -s f -l format -d 'Output format'
complete -c strptime -s i -l input-format -d 'Input format, can be used multiple times'
complete -c strptime -s e -l backslash-escapes -d 'Enable interpretation of backslash escapes in the output and input format spe…'
complete -c strptime -s S -l sed-mode -d 'Copy parts from the input before and after a matching date/time'
complete -c strptime -s l -l locale -d 'Make internal strptime(3) and strftime(3) behave in a locale dependent way, d…'

