# tftp
# Autogenerated from man page /usr/share/man/man1/tftp.1.gz
complete -c tftp -s 4 -d 'Connect with IPv4 only, even if IPv6 support was compiled in'
complete -c tftp -s 6 -d 'Connect with IPv6 only, if compiled in'
complete -c tftp -s c -d 'Execute command as if it had been entered on the tftp prompt'
complete -c tftp -s l -d 'Default to literal mode'
complete -c tftp -s m -d 'Set the default transfer mode to mode.   This is usually used with -c'
complete -c tftp -s R -d 'Force the originating port number to be in the specified range of port numbers'
complete -c tftp -s v -d 'Default to verbose mode'
complete -c tftp -s V -d 'Print the version number and configuration to standard output, then exit grac…'

