# update-crypto-policies
# Autogenerated from man page /usr/share/man/man8/update-crypto-policies.8.gz
complete -c update-crypto-policies -l show -d 'oc o 2. 3'
complete -c update-crypto-policies -l is-applied -d 'oc o 2. 3'
complete -c update-crypto-policies -l set
complete -c update-crypto-policies -l no-check -d 'oc o 2. 3'
complete -c update-crypto-policies -l no-reload
complete -c update-crypto-policies -o 'Djava.security.properties' -d 'oc o 2. 3'

