# winln
# Autogenerated from man page /usr/share/man/man1/winln.1.gz
complete -c winln -s s -l symbolic -d 'Create a symbolic (as opposed to hard) link'
complete -c winln -s v -l verbose -d 'Print to standard output the names of links created'
complete -c winln -s f -l force -d 'Replace existing destination file'
complete -c winln -s d -l directory -d 'Create a directory symbolic link'
complete -c winln -s F -l file -d 'Create a file symbolic link'
complete -c winln -s A -l auto -d 'Automatically determine the type of symbolic link to create'
complete -c winln -s t -l target-directory -d 'Treat DIRECTORY as the directory in which to create links based on the remain…'
complete -c winln -s T -l no-target-directory -d 'Treat LINKNAME as a normal file always'
complete -c winln -s h -l help -d 'Show brief help message'
complete -c winln -l version -d 'Display version information'
complete -c winln -s b -l backup
complete -c winln -s i -l interactive
complete -c winln -s L -l logical
complete -c winln -s n -l no-dereference
complete -c winln -s P -l physical

