# wput
# Autogenerated from man page /usr/share/man/man1/wput.1.gz
complete -c wput -s V
complete -c wput -l version -d 'Display the version of wput'
complete -c wput -s h
complete -c wput -l help -d 'Print a help screen, with a short description of wput\'s command-line options'
complete -c wput -s b
complete -c wput -l background -d 'Go to background immediately after startup'
complete -c wput -s o
complete -c wput -l output-file -d 'Log all messages to logfile'
complete -c wput -s a
complete -c wput -l append-output -d 'Append all logged messages to logfile'
complete -c wput -s q
complete -c wput -l quiet -d 'Turn off Wput\'s output'
complete -c wput -s v
complete -c wput -l verbose -d 'Turn on verbose output'
complete -c wput -o nv
complete -c wput -l less-verbose -d 'Be less verbose.  That means reducing Wput\'s output to a minimum'
complete -c wput -s i
complete -c wput -l input-file -d 'Reads URLs and filenames from file'
complete -c wput -s s
complete -c wput -l sort -d 'If sorting is enabled Wput first reads all URLs from any input-devices availa…'
complete -c wput -l basename -d 'This option causes Wput to snip path from all input-files when they are conne…'
complete -c wput -s I
complete -c wput -l input-pipe -d 'If no file/directory can be "guessed" (see "Guessing Local File") from the UR…'
complete -c wput -s R
complete -c wput -l remove-source-files -d 'Unlinks/deletes files that have been successfully transmitted'
complete -c wput -l bind-address
complete -c wput -s t
complete -c wput -l tries -d 'Set number of retries to number'
complete -c wput -o nc
complete -c wput -l dont-continue -d 'If this flag is specified, resuming will be turned off, meaning that a remote…'
complete -c wput -s u
complete -c wput -l reupload -d 'If this flag is specified, a remote file having the same size as the local on…'
complete -c wput -l skip-larger -d 'If this flag is specified, a remote file being larger than the local one will…'
complete -c wput -l skip-existing -d 'If this flag is specified, the upload of a file will be skipped if the remote…'
complete -c wput -s N
complete -c wput -l timestamping -d 'If timestamping is enabled, Wput will retrieve a directory list and parse it …'
complete -c wput -s l
complete -c wput -l limit-rate
complete -c wput -l no-directories -d 'If Wput is unable to CWD into a directory, it will try to create it'
complete -c wput -s Y
complete -c wput -l proxy -d 'MODE can be either http for http-based proxies (such as SQUID), socks for SOC…'
complete -c wput -l proxy-user
complete -c wput -l proxy-pass
complete -c wput -s p
complete -c wput -l port-mode
complete -c wput -s A
complete -c wput -l ascii
complete -c wput -s B
complete -c wput -l binary -d 'Specifying this flag forces Wput to use BINARY mode file transfers'
complete -c wput -o mMODE
complete -c wput -l chmod -d 'This will change the access mode of the transferred files'
complete -c wput -l force-tls

